### ISSUE TITLE
Direct link to metro/fluent skins

### ISSUE THREAD

**Issue by PhantomGamers** [xamionex/steam-skins-wiki#4]
The link to download the [AikoMidori/SteamSkins](https://github.com/AikoMidori/SteamSkins) repo could be replaced with a direct link to the download for the individual folders.

e.g. :

Metro - https://download-directory.github.io/?url=https://github.com/AikoMidori/SteamSkins/tree/main/Metro/

Fluent - https://download-directory.github.io/?url=https://github.com/AikoMidori/SteamSkins/tree/main/Fluent/

and then the Metro-JS version could also be directly linked:

Metro-JS - https://download-directory.github.io/?url=https://github.com/AikoMidori/SteamSkins/tree/main/Metro/Metro-JS/

Though the Metro-JS link does not work perfectly as the resulting zip still has `Metro` as its root folder with `Metro-JS` being a subfolder. I opened an issue on the download-directory github repo about this https://github.com/download-directory/download-directory.github.io/issues/98

**Comment by xamionex** [comment]
Added the separated downloads, no need to include metro-js cause it's downloaded with metro

**Comment by PhantomGamers** [comment]
> Added the separated downloads, no need to include metro-js cause it's downloaded with metro

Yeah but it needs to be copied to skins separately

**Comment by xamionex** [comment]
I'll test it out to see how it works

**Comment by xamionex** [comment]
Added a note for it, tell me what you think

https://a31725c3.steamskins.pages.dev/guides/installation/#installing-a-theme

**Comment by PhantomGamers** [comment]
I made some changes to that here https://github.com/xamionex/steamskins/pull/6

To clarify SFP behavior:

If you have loose files they should go in `steamui`, if you want to use a skin folder files should go in `Steam/steamui/skins/{FOLDERNAME}`. Loose files in `Steam/steamui/skins` will never be read.

Also just fwiw `it's` is short for `it is`, `its` is the possessive word.

Oh and also the Space Theme skin does also works with SFP as SFP supports Millennium's config.json format as well

**Comment by xamionex** [comment]
Didn't know, also for the repeated mistakes with its and it's mismatching here and there and also copy pasted things all over the place is because I don't really have much time to work on this and I just try doing my best under a time limit when someone's talking with me :P 
That's why I asked you guys to help in the first place ^^

**Comment by PhantomGamers** [comment]
Yeah np, I didn't mean anything by it I was just letting you know for future reference haha :)

**Comment by xamionex** [comment]
Thanks anyway, also you can test on your pc by installing retype just so you know
You gotta have npm and then you can install retypeapp with it
then host a local server with retype start

https://retype.com/#quick-start
