### ISSUE TITLE
Add additional skins

### ISSUE THREAD

**Issue by PhantomGamers** [xamionex/steam-skins-wiki#5]
There are a few other skins that are available that are not currently listed on the website.

There is the Dark Mode skin for the steam community and store pages here [AikoMidori/steam-dark-mode](AikoMidori/steam-dark-mode)

There is a fork of that skin that has a little more features (though AikoMidori is working on a big update to the original version) here, which I am currently using myself [BallOpener/steam-dark-mode/blob/beta2/css/webkit.css](https://raw.githubusercontent.com/BallOpener/steam-dark-mode/beta2/css/webkit.css)

RoseTheFlower has a friends skin (and wip library and I think client skin) here [RoseTheFlower/newsteamchat](https://github.com/RoseTheFlower/newsteamchat)

**Comment by xamionex** [comment]
Added all of the mentioned, thank you!
