### ISSUE TITLE
Add Adwaita for Steam

### ISSUE THREAD

**Issue by JunkiEDM** [xamionex/steam-skins-wiki#9]
https://github.com/tkashkin/Adwaita-for-Steam
Mostly targeted towards Linux users as it tries to mimic the GNOME UI but it [works on Windows too](https://github.com/tkashkin/Adwaita-for-Steam#windows-install), looks like a nice skin :)

**Comment by xamionex** [comment]
I'm gonna add it, just know that I'm not gonna add previews as they have their own guide and previews, I will just link it.

**Comment by xamionex** [comment]
Added in d0666306c63ffb0675eafa6d73a02d05b3de2119
Re-open if you don't like it
